# 長度都是 20480

In [68]:
# 列出 ims_bearing 裡頭所有子目錄的 csv 檔案
import os
import pandas as pd
path = 'ims_bearing'
for root, dirs, files in os.walk(path):
    for file in files[:3]:
        print(os.path.join(root, file))
        try:
            df = pd.read_csv(file, sep='\t', header=None)
            print(len(df))
            print(df.head())
            print(df.tail())
        except:
            pass

ims_bearing/Readme Document for IMS Bearing Data.pdf
ims_bearing/archive.zip
ims_bearing/2nd_test/2nd_test/2004.02.17.18.52.39
ims_bearing/2nd_test/2nd_test/2004.02.13.01.12.39
ims_bearing/2nd_test/2nd_test/2004.02.19.04.22.39
ims_bearing/1st_test/1st_test/2003.11.01.11.41.44
ims_bearing/1st_test/1st_test/2003.11.01.02.21.44
ims_bearing/1st_test/1st_test/2003.11.18.14.32.30
ims_bearing/3rd_test/4th_test/txt/2004.03.25.16.51.57
ims_bearing/3rd_test/4th_test/txt/2004.04.17.02.22.55
ims_bearing/3rd_test/4th_test/txt/2004.04.06.12.21.57


In [21]:
# open "csv_data/avg_concat_dataset_1.csv" (python)
import pandas as pd
df = pd.read_csv("csv_data/avg_concat_dataset_1.csv")
print(len(df))
print(df.head())
print(df.tail())

2156
            Unnamed: 0    b1_ch1    b1_ch2    b2_ch3    b2_ch4    b3_ch5  \
0  2003-10-22 12:06:24  0.104144  0.100250  0.107151  0.102002  0.106148   
1  2003-10-22 12:09:13  0.103652  0.099853  0.108190  0.102922  0.106660   
2  2003-10-22 12:14:13  0.105036  0.101540  0.108548  0.104041  0.108741   
3  2003-10-22 12:19:13  0.104898  0.101570  0.108150  0.103379  0.108073   
4  2003-10-22 12:24:13  0.104776  0.102188  0.107943  0.102626  0.108453   

     b3_ch6    b4_ch7    b4_ch8  
0  0.108152  0.094804  0.099515  
1  0.108453  0.095070  0.093585  
2  0.109881  0.096157  0.098300  
3  0.110006  0.096813  0.098600  
4  0.109349  0.096359  0.098468  
               Unnamed: 0    b1_ch1    b1_ch2    b2_ch3    b2_ch4    b3_ch5  \
2151  2003-11-25 16:07:32  0.138781  0.130003  0.151368  0.138563  0.209854   
2152  2003-11-25 23:13:21  0.142146  0.131044  0.162769  0.149215  0.339316   
2153  2003-11-25 23:19:56  0.142098  0.131344  0.167268  0.154293  0.357835   
2154  2003-11-25 2

In [22]:
import pandas as pd
# 只讀取前 10 項目
df = pd.read_csv('csv_data/fft_dataset_1.csv', nrows=50000)
# 顯示結果
print(df)

                      date        b1_ch1        b1_ch2        b2_ch3  \
0      2003-10-22 12:06:24  5.119589e+06  5.108868e+06  5.111375e+06   
1      2003-10-22 12:06:24  7.383400e+04  7.393105e+04  7.380612e+04   
2      2003-10-22 12:06:24  7.125052e+04  7.120187e+04  7.101303e+04   
3      2003-10-22 12:06:24  6.510619e+04  6.556233e+04  6.499503e+04   
4      2003-10-22 12:06:24  6.271328e+04  6.206245e+04  6.190362e+04   
...                    ...           ...           ...           ...   
49995  2003-10-22 12:14:13  3.818222e+02  3.500611e+02  3.252055e+02   
49996  2003-10-22 12:14:13  8.823327e+02  4.311399e+02  1.896097e+02   
49997  2003-10-22 12:14:13  2.253729e+02  5.971241e+02  3.620366e+02   
49998  2003-10-22 12:14:13  2.101041e+02  6.188112e+02  6.091051e+02   
49999  2003-10-22 12:14:13  5.189123e+02  4.861485e+02  2.371682e+02   

             b2_ch4        b3_ch5        b3_ch6        b4_ch7        b4_ch8  
0      5.106550e+06  4.978927e+06  4.984062e+06  4.982843

In [52]:
_ = df[df['date'] == "2003-10-22 12:06:24"]
_

date        b1_ch1        b1_ch2        b2_ch3  \
0      2003-10-22 12:06:24  5.119589e+06  5.108868e+06  5.111375e+06   
1      2003-10-22 12:06:24  7.383400e+04  7.393105e+04  7.380612e+04   
2      2003-10-22 12:06:24  7.125052e+04  7.120187e+04  7.101303e+04   
3      2003-10-22 12:06:24  6.510619e+04  6.556233e+04  6.499503e+04   
4      2003-10-22 12:06:24  6.271328e+04  6.206245e+04  6.190362e+04   
...                    ...           ...           ...           ...   
20475  2003-10-22 12:06:24  2.368670e+02  5.272867e+02  7.752849e+01   
20476  2003-10-22 12:06:24  3.234646e+02  3.780511e+02  1.307320e+02   
20477  2003-10-22 12:06:24  1.754604e+02  8.622013e+02  1.324796e+02   
20478  2003-10-22 12:06:24  5.117090e+02  3.521754e+02  2.616373e+02   
20479  2003-10-22 12:06:24  6.461889e+02  4.829047e+01  4.422110e+02   

             b2_ch4        b3_ch5        b3_ch6        b4_ch7        b4_ch8  
0      5.106550e+06  4.978927e+06  4.984062e+06  4.982843e+06  4.977161e+06  
1      7.386224e+04  7.493522e+04  7.081826e+04  7.159109e+04  6.415226e+04  
2      7.158672e+04  7.350542e+04  6.922753e+04  7.277226e+04  6.603898e+04  
3      6.495063e+04  6.795313e+04  6.428079e+04  6.317480e+04  5.856575e+04  
4      6.224671e+04  6.404001e+04  6.095201e+04  6.101940e+04  6.014753e+04  
...             ...           ...           ...           ...           ...  
20475  3.301957e+02  4.150420e+02  4.809046e+02  4.720241e+02  3.922110e+02  
20476  4.765706e+02  5.768678e+02  4.905335e+02  2.774201e+02  5.043436e+02  
20477  4.032614e+02  8.390634e+02  6.591582e+02  4.620751e+02  4.488147e+02  
20478  2.507592e+02  2.953248e+02  4.943595e+02  1.503133e+02  5.448555e+02  
20479  2.583418e+02  6.169873e+02  7.692588e+02  4.295356e+02  2.919584e+02  

[20480 rows x 9 columns]

In [53]:
__ = _['b1_ch1']
__

0        5.119589e+06
1        7.383400e+04
2        7.125052e+04
3        6.510619e+04
4        6.271328e+04
             ...     
20475    2.368670e+02
20476    3.234646e+02
20477    1.754604e+02
20478    5.117090e+02
20479    6.461889e+02
Name: b1_ch1, Length: 20480, dtype: float64

In [27]:
_ = df[df['date'] == "2003-10-22 12:06:24"] 
(_['b1_ch1']/_['b1_ch1'].max())

0        1.000000
1        0.014422
2        0.013917
3        0.012717
4        0.012250
           ...   
20475    0.000046
20476    0.000063
20477    0.000034
20478    0.000100
20479    0.000126
Name: b1_ch1, Length: 20480, dtype: float64

In [51]:
from scipy.fft import fft
from scipy.signal import detrend
import pandas as pd
df1 = pd.read_csv("ims_bearing/1st_test/1st_test/2003.10.22.12.06.24", sep='\t', header=None)
____ = abs(fft(df1[0].values)[1:])
____[:5], ____[-5:]

(array([15.03276443,  8.62930023, 11.82992191,  2.98899442,  6.09105752]),
 array([ 6.09105752,  2.98899442, 11.82992191,  8.62930023, 15.03276443]))

In [12]:
total_rows = sum(1 for line in open('csv_data/fft_dataset_1.csv'))
total_rows

44154881

In [69]:
44154880/20480

2156.0

In [8]:
# 找出這資料夾裡面有多少檔案 ims_bearing/3rd_test
import os

path = 'ims_bearing/3rd_test/4th_test/txt'
files = os.listdir(path)
print(len(files))

6324


In [59]:
from scipy.signal import detrend
detrend([3,4,5])

array([-1.33226763e-15, -8.88178420e-16,  0.00000000e+00])

In [5]:
import os
import numpy as np
import pandas as pd
from natsort import natsorted
from scipy.fft import fft
from scipy.signal import detrend


def dir_list(path=None):
    """
    :param path: path to the dataset
    :return: an order directory list
    """
    list_dir = natsorted(os.listdir(path))
    return list_dir


def concat_raw_data(path=None, csv_path=None, dataset=None, fourier_tr=True,
                    detrends=True):
    """
    :param detrends: boolean to detrend the signal
    :param fourier_tr: boolean tranfor singal with furier transform
    :param path: a path to the dataset file
    :param dataset: number of the dataset to be processes from the three dataset available
    :param csv_path: path save the contenated files into a csv file
    :return: data dataset with average and std from each file at each time step
    """

    list_dir = dir_list(path)

    col_dual = list()
    for b in range(0, 4):
        b1 = f'b{b + 1}_ch{b * 2 + 1}'
        b2 = f'b{b + 1}_ch{b * 2 + 2}'
        col_dual.extend([b1, b2])

    col_names = [f'b{i + 1}_ch{i + 1}' for i in range(0, 4)]

    dataset_dict = {}

    for i, f in enumerate(list_dir):
        temp_df = pd.read_csv(os.path.join(path, f), sep='\t', header=None)
        if len(temp_df.columns) == 8:
            temp_df.columns = col_dual
        else:
            temp_df.columns = col_names
        temp_df.insert(0, 'date', len(temp_df) * [f])
        dataset_dict[f] = temp_df

    df = pd.concat(list(dataset_dict.values()), ignore_index=True)
    df.set_index('date', inplace=True)
    df.index = pd.to_datetime(df.index, format='%Y.%m.%d.%H.%M.%S')

    os.makedirs(csv_path, exist_ok=True)

    if fourier_tr:
        return fourier_transforms(df, path=csv_path, dataset=dataset, detrends=detrends)

    else:
        fname = os.path.join(csv_path, f'concat_dataset_{dataset}.csv')

        return df.to_csv(fname)


def fourier_transforms(data_frame, path=None, dataset=1, detrends=True):
    """
    :param data_frame: datafram with the concatenated raw data
    :param path: a path to store the csv file
    :param dataset: number of dataste processed
    :param detrends: a boolean to detrend before applyin fourier transformations
    :return: save dataframe as csv
    """

    os.makedirs(path, exist_ok=True)
    fname = os.path.join(path, f'fft_dataset_{dataset}.csv')
    df_fft = data_frame.copy()

    for col in df_fft.columns:
        if detrends:
            fft_col = fft(detrend(df_fft[col].values))
        else:
            fft_col = fft(df_fft[col].values)

        df_fft[col] = np.abs(fft_col)

    return df_fft.to_csv(fname)


def average_signal_dataset(path=None, dataset=1, csv_path=None):
    """
    :param path:  str a path to the dataset file
    :param dataset:  int the number of the daset to be process
    :param csv_path:  str a path to save the datframes to csv file
    :return: data dataset with average and std from each file at each time step
    """
    list_dir = dir_list(path)

    if dataset == 1:
        col_names = list()
        for b in range(0, 4):
            b1 = f'b{b + 1}_ch{b * 2 + 1}'
            b2 = f'b{b + 1}_ch{b * 2 + 2}'
            col_names.extend([b1, b2])
    else:
        col_names = [f'b{i + 1}_ch{i + 1}' for i in range(0, 4)]

    dataset_dict = {}

    for file in list_dir:
        temp_df = pd.read_csv(os.path.join(path, file), sep='\t', header=None)
        # mean_std_values = np.append(temp_df.abs().mean().values, temp_df.abs().std().values)
        mean = temp_df.abs().mean().values
        dataset_dict[file] = mean

    df = pd.DataFrame.from_dict(dataset_dict, orient='index', columns=col_names)
    df.index = pd.to_datetime(df.index, format='%Y.%m.%d.%H.%M.%S')
    os.makedirs(csv_path, exist_ok=True)

    fname = os.path.join(csv_path, f'avg_concat_dataset_{dataset}.csv')

    return df.to_csv(fname)


def generate_datasets(datasets_dict=None, csv_path=None):
    for i, (k, v) in enumerate(datasets_dict.items()):
        dataset_num = i + 1
        print(i,k,v)
        # average_signal_dataset(v, dataset=dataset_num, csv_path=csv_path)
        # concat_raw_data(v, csv_path, dataset=dataset_num, fourier_tr=True, detrends=False)


datasets = {'dataset_path1': './ims_bearing/1st_test/1st_test',
            'dataset_path2': './ims_bearing/2nd_test/2nd_test',
            'dataset_path3': './ims_bearing/3rd_test/4th_test/txt'}

csv_dir = os.path.join(os.getcwd(), 'csv_data')
os.makedirs(csv_dir, exist_ok=True)

generate_datasets(datasets, csv_path=csv_dir)

0 dataset_path1 ./ims_bearing/1st_test/1st_test
1 dataset_path2 ./ims_bearing/2nd_test/2nd_test
2 dataset_path3 ./ims_bearing/3rd_test/4th_test/txt


In [1]:
# import gdown

# # Google Drive 檔案的分享連結
# url = "https://drive.google.com/file/d/1IYO-5MkHCZp-IYQ-44jPxR1Ux4t_NABR/view?usp=sharing"

# # 目標檔案的存放位置
# output = "archive.zip"  # 替換為你的檔案名稱和格式，例如 example.txt, model.pth 等

# # 使用 gdown 下載
# gdown.download(url, output, quiet=False)

# print(f"檔案已下載到: {output}")

/home/kycho/timeseries-sensor-anomaly-detection/.conda/lib/python3.11/site-packages/gdown/parse_url.py:48: UserWarning: You specified a Google Drive link that is not the correct link to download a file. You might want to try `--fuzzy` option or the following url: https://drive.google.com/uc?id=1IYO-5MkHCZp-IYQ-44jPxR1Ux4t_NABR
  warnings.warn(
Downloading...
From: https://drive.google.com/file/d/1IYO-5MkHCZp-IYQ-44jPxR1Ux4t_NABR/view?usp=sharing
To: /home/kycho/timeseries-sensor-anomaly-detection/archive.zip
92.9kB [00:00, 6.71MB/s]

檔案已下載到: archive.zip
